### ISSUE TITLE
Warrior card tooltip crashed the game while I was playing a diff mod class

### ISSUE THREAD

**Issue by SilentJ28** [yhrcyt/StS-TheWarriorMod#4]
**Crash reports**
If the game crashed because of this bug, please show me the crash report or game log.
The game log can be found in {game directory}\sendToDevs\logs\SlayTheSpire.log

**Describe the bug**
Game crashed when I hovered what I assume was a warrior card 

**To Reproduce**
Was playing as Blackbeard (diff mod char)
Picked a boss relic that let me pick 1 card from each rarity. This seemed to pick across all the modded characters I had installed.
When I hovered over the 3rd card in a selection the game instantly crashed.
Log showed a call stack including a Warrior method involving tooltip (which was what was about to render when the crash occurred)

06:28:59.340 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at beaked.patches.DynamicPluralizePatch$RenderDescription.Prefix(DynamicPluralizePatch.java:22) ~[BeakedTheCultist.jar:?]
	at com.megacrit.cardcrawl.cards.AbstractCard.renderDescription(AbstractCard.java) ~[?:?]
	at com.megacrit.cardcrawl.cards.AbstractCard.renderCard(AbstractCard.java:1166) ~[?:?]
	at com.megacrit.cardcrawl.cards.AbstractCard.render(AbstractCard.java:1131) ~[?:?]
	at com.megacrit.cardcrawl.cards.AbstractCard.render(AbstractCard.java:1079) ~[?:?]
	at thewarrior.cards.AbstractWarriorAttackCard.renderCardTip(AbstractWarriorAttackCard.java:258) ~[TheWarrior.jar:?]
	at com.megacrit.cardcrawl.screens.CardRewardScreen.renderCardReward(CardRewardScreen.java:344) ~[?:?]
	at com.megacrit.cardcrawl.screens.CardRewardScreen.render(CardRewardScreen.java:333) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.render(AbstractDungeon.java:2716) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:479) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Mod list**
Basemod, stslib, hubris, infinite spire, blakkmod, replay the spire, beaked, disciple, mad scientist, blackbeard, warrior, construct, friendly minions, yohane, mystic

Was playing as Blackbeard
Boss relic was from either Infinite Spire or Replay the Spire (most likely replay)
Card that crashed me was from this mod

**Comment by yhrcyt** [comment]
I understand.

**Comment by yhrcyt** [comment]
"BeakedTheCultist" mod overrides renderDescription method. and that method tries to get my cardID when my cardID is set to null.

**Comment by yhrcyt** [comment]
Fixed. alpha 0.0.3 will be released as soon as I finished fixing another bug.
