### ISSUE TITLE
Game freeze and card error

### ISSUE THREAD

**Issue by Sunstreak13** [yhrcyt/StS-TheWarriorMod#8]
I played spike shield with one energy and my game froze I copied what i think the error is below.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.ExceptionInInitializerError
	at thewarrior.cards.SpikyShield.use(SpikyShield.java:66)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1565)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:151)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:267)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2514)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:881)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:460)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.NullPointerException
	at thewarrior.powers.SpikyShieldPower.<clinit>(SpikyShieldPower.java:16)
	... 10 more
Also I comboed  scratch (i think) on two scratch cards multiple time the first time caused a visual error of the scratch card and the second combo caused a glitched version of the combo card in my draw pile that counted as two cards forced together and does it's effect once for one energy, hope this helps and sorry for breaking your mod.

**Comment by yhrcyt** [comment]
"Also I comboed scratch (i think) on two scratch cards multiple time the first time caused a visual error of the scratch card and the second combo caused a glitched version of the combo card in my draw pile that counted as two cards forced together and does it's effect once for one energy, hope this helps and sorry for breaking your mod."

Can you provide any further information?
I fixed the game freeze bug and the patch will be released soon.

But I don't quite understand what happened during that combo. Can you provide description with more detail?

**Comment by yhrcyt** [comment]
Do you have other mods on? Send me the game log might help.
