### ISSUE TITLE
Spiky shield crash  

### ISSUE THREAD

**Issue by 5m1l35** [yhrcyt/StS-TheWarriorMod#9]
Before reporting this bug, please check your mod version. All of your mods need to be up-to-date.

**Crash reports**
If the game crashed because of this bug, please show me the crash report or game log.
The game log can be found in {game directory}\sendToDevs\logs\SlayTheSpire.log
[SlayTheSpire_201810152204_1.log](https://github.com/yhrcyt/StS-TheWarriorMod/files/2480753/SlayTheSpire_201810152204_1.log)
**Describe the bug**
froze the entire game for some reason 

**To Reproduce**
1. was in champion fight 
2. used spiky shield in my first turn with one energy

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.ExceptionInInitializerError
	at thewarrior.cards.SpikyShield.use(SpikyShield.java:66)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1565)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:151)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:267)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2514)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:881)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:460)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.NullPointerException
	at thewarrior.powers.SpikyShieldPower.<clinit>(SpikyShieldPower.java:16)
	... 10 more
If there is any other data I can provide I will be happy to do so. I also noticed that sometimes the choice cards seem to become cards in my deck in there own right not sure if this was a feature or a bug so I did not report it as such.

**Comment by yhrcyt** [comment]
Fixed. Patch will be released soon.
